---
version: 2
jobs:
  build_and_test:
    working_directory: ~/sfdx-plugin-lwc-test

    docker:
      - image: circleci/node:lts

    steps:
      - checkout

      - restore_cache:
          keys:
          - yarn-v3-{{ checksum "yarn.lock" }}

      - run:
          name: Install dependencies
          command: yarn

      - run:
          name: Build
          command: yarn build

      - run:
        name: Check License Headers
        command: yarn check-license-headers

      - run:
          name: Testing
          command: yarn test

      - save_cache:
          paths:
            - ~/.cache/yarn
            - yarn.lock
            - node_modules
          key: yarn-v3-{{ checksum "yarn.lock" }}

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
