---
version: 2
jobs:
  node-latest: &test
    docker:
      - image: node:latest
    working_directory: ~/sfdx-plugin-lwc-test
    steps:
      - checkout
      - restore_cache:
          keys:
          - yarn-v3-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Build
          command: yarn build
      - run:
          name: Testing
          command: yarn test
      - save_cache:
          paths:
            - ~/.cache/yarn
            - yarn.lock
            - node_modules
          key: yarn-v3-{{ checksum "yarn.lock" }}
  node-8:
    <<: *test
    docker:
      - image: node:8

workflows:
  version: 2
  main_workflow:
    jobs:
      - node-latest
      - node-8
